### PR TITLE
Support rainbow-mode by advice-add

### PR DESCRIPTION
**Pull request by tsuu32**
I found rainbow-mode related comment out in zenburn-theme.el and I did some fixes to use `advice-add`.

### CODE REVIEW

**Comment by bbatsov** [comment]
Did you also see https://github.com/bbatsov/zenburn-emacs/pull/315 by @tarsius?

**Comment by tsuu32** [comment]
Thanks for your comment!
Yes, but I prefer `advice-add` to `defadvice`.
The main defference is mine use `zenburn-colors-alist` which had removed  in the past.

**Comment by tsuu32** [comment]
@tarsius thanks for your review!
> Well "fix" is relative. I would settle for "change".

That’s right. I made commit message without thinking so much. Sorry.

> My advice is to drop such changes unless you care strongly about it and are prepared to explain why your way is significantly better.

I think `--` is often used after package or module name. `zenburn-advice--rainbow-turn-on` looks like `zenburn-advice` package exist, so I think `zenburn--advice-rainbow-turn-on` is better.
And I found similar examples in helm package. (https://github.com/emacs-helm/helm/blob/12c50cf2a3748f44eb8c8ccad89ebd6e63fe99f6/helm-files.el#L2269)

Should I revert it?

**Comment by bbatsov** [comment]
Superseded by #315.

**Pull request closed without merging**
