### PR TITLE
Customize company-quickhelp colors

### PR DESCRIPTION
**Pull request by arichiardi**

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks!

**Comment by arichiardi** [comment]
I have a question though, what happens when the vars are not defined (actually are defined later in the init file)? I guess no errors are thrown as I don't see any but also the colors are missing..

**Comment by basil-conto** [comment]
The settings added in this PR are in the wrong place. They are variables, not faces, so they should go under `custom-theme-set-variables`, not `custom-theme-set-faces`.

Apart from that, custom themes are free to apply settings to as-of-yet undefined variables/faces. The settings only take effect when the theme is enabled and if/when the variables/faces are defined and used.

**Comment by arichiardi** [comment]
Oh that is why I was not able to see them, sorry I am a bit of a newbie on these things

**Comment by basil-conto** [comment]
No harm done (except perhaps some error messages on your end :). Just open a new PR moving the settings to the `custom-theme-set-variables` call near the end of `zenburn-theme.el`.

**Comment by arichiardi** [comment]
Will do

**Pull request merged**
