### PR TITLE
Realgud

### PR DESCRIPTION
**Pull request by rocky**
Try boxed attribute in font face for enable/disabled breakpoints

### CODE REVIEW

**Comment by rocky** [comment]
This might be a little better. Here is a current screenshot: 

zenburn-current

And here is the proposed change: 

zenburn-boxed

Since I am bad at style, please feel free to ignore this if you think the current is better, or change as you see fit.

**Comment by basil-conto** [comment]
FWIW, looks good to me. I would only suggest rebasing on top of current `master`.

**Comment by rocky** [comment]
Not sure what the best way to do is, but will try that....

**Comment by rocky** [comment]
Ok. I think that does it (although I make lots of mistakes which is why I work on debuggers).

**Comment by basil-conto** [comment]
Looks fine to me. :)

P.S. I think `:style` defaults to `nil` anyway, but there's no harm in stating it explicitly.

**Pull request merged**
